/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This code was generated by avrogencpp 1.13.0-SNAPSHOT. Do not edit.*/

#ifndef MANIFEST_HPP_1989521603_H
#define MANIFEST_HPP_1989521603_H


#include <sstream>
#include <any>
#include <utility>
#include "avro/Specific.hh"
#include "avro/Encoder.hh"
#include "avro/Decoder.hh"

struct _manifest_list_json_Union__0__ {
private:
    size_t idx_;
    std::any value_;
public:
    /** enum representing union branches as returned by the idx() function */
    enum class Branch: size_t {
        null = 0,
        bool_ = 1,
    };
    size_t idx() const { return idx_; }
    Branch branch() const { return static_cast<Branch>(idx_); }
    bool is_null() const {
        return (idx_ == 0);
    }
    void set_null() {
        idx_ = 0;
        value_ = std::any();
    }
    const bool& get_bool() const;
    bool& get_bool();
    void set_bool(const bool& v);
    void set_bool(bool&& v);
    _manifest_list_json_Union__0__();
};

struct _manifest_list_json_Union__1__ {
private:
    size_t idx_;
    std::any value_;
public:
    /** enum representing union branches as returned by the idx() function */
    enum class Branch: size_t {
        null = 0,
        bytes = 1,
    };
    size_t idx() const { return idx_; }
    Branch branch() const { return static_cast<Branch>(idx_); }
    bool is_null() const {
        return (idx_ == 0);
    }
    void set_null() {
        idx_ = 0;
        value_ = std::any();
    }
    const std::vector<uint8_t>& get_bytes() const;
    std::vector<uint8_t>& get_bytes();
    void set_bytes(const std::vector<uint8_t>& v);
    void set_bytes(std::vector<uint8_t>&& v);
    _manifest_list_json_Union__1__();
};

struct field_summary {
    typedef _manifest_list_json_Union__0__ contains_nan_t;
    typedef _manifest_list_json_Union__1__ lower_bound_t;
    typedef _manifest_list_json_Union__1__ upper_bound_t;
    bool contains_null;
    contains_nan_t contains_nan;
    lower_bound_t lower_bound;
    upper_bound_t upper_bound;
    field_summary() :
        contains_null(bool()),
        contains_nan(contains_nan_t()),
        lower_bound(lower_bound_t()),
        upper_bound(upper_bound_t())
        { }
};

struct manifest_file {
    std::string manifest_path;
    int32_t manifest_length;
    int32_t partition_spec_id;
    int32_t content;
    int32_t sequence_number;
    int32_t min_sequence_number;
    int32_t added_snapshot_id;
    int32_t added_data_files_count;
    int32_t existing_data_files_count;
    int32_t deleted_data_files_count;
    int32_t added_rows_count;
    int32_t existing_rows_count;
    int32_t deleted_rows_count;
    std::vector<field_summary > partitions;
    manifest_file() :
        manifest_path(std::string()),
        manifest_length(int32_t()),
        partition_spec_id(int32_t()),
        content(int32_t()),
        sequence_number(int32_t()),
        min_sequence_number(int32_t()),
        added_snapshot_id(int32_t()),
        added_data_files_count(int32_t()),
        existing_data_files_count(int32_t()),
        deleted_data_files_count(int32_t()),
        added_rows_count(int32_t()),
        existing_rows_count(int32_t()),
        deleted_rows_count(int32_t()),
        partitions(std::vector<field_summary >())
        { }
};

inline
const bool& _manifest_list_json_Union__0__::get_bool() const {
    if (idx_ != 1) {
        throw avro::Exception("Invalid type for union _manifest_list_json_Union__0__");
    }
    return *std::any_cast<bool >(&value_);
}

inline
bool& _manifest_list_json_Union__0__::get_bool() {
    if (idx_ != 1) {
        throw avro::Exception("Invalid type for union _manifest_list_json_Union__0__");
    }
    return *std::any_cast<bool >(&value_);
}

inline
void _manifest_list_json_Union__0__::set_bool(const bool& v) {
    idx_ = 1;
    value_ = v;
}

inline
void _manifest_list_json_Union__0__::set_bool(bool&& v) {
    idx_ = 1;
    value_ = std::move(v);
}

inline
const std::vector<uint8_t>& _manifest_list_json_Union__1__::get_bytes() const {
    if (idx_ != 1) {
        throw avro::Exception("Invalid type for union _manifest_list_json_Union__1__");
    }
    return *std::any_cast<std::vector<uint8_t> >(&value_);
}

inline
std::vector<uint8_t>& _manifest_list_json_Union__1__::get_bytes() {
    if (idx_ != 1) {
        throw avro::Exception("Invalid type for union _manifest_list_json_Union__1__");
    }
    return *std::any_cast<std::vector<uint8_t> >(&value_);
}

inline
void _manifest_list_json_Union__1__::set_bytes(const std::vector<uint8_t>& v) {
    idx_ = 1;
    value_ = v;
}

inline
void _manifest_list_json_Union__1__::set_bytes(std::vector<uint8_t>&& v) {
    idx_ = 1;
    value_ = std::move(v);
}

inline _manifest_list_json_Union__0__::_manifest_list_json_Union__0__() : idx_(0) { }
inline _manifest_list_json_Union__1__::_manifest_list_json_Union__1__() : idx_(0) { }
namespace avro {
template<> struct codec_traits<_manifest_list_json_Union__0__> {
    static void encode(Encoder& e, _manifest_list_json_Union__0__ v) {
        e.encodeUnionIndex(v.idx());
        switch (v.idx()) {
        case 0:
            e.encodeNull();
            break;
        case 1:
            avro::encode(e, v.get_bool());
            break;
        }
    }
    static void decode(Decoder& d, _manifest_list_json_Union__0__& v) {
        size_t n = d.decodeUnionIndex();
        if (n >= 2) { throw avro::Exception("Union index too big"); }
        switch (n) {
        case 0:
            d.decodeNull();
            v.set_null();
            break;
        case 1:
            {
                bool vv;
                avro::decode(d, vv);
                v.set_bool(std::move(vv));
            }
            break;
        }
    }
};

template<> struct codec_traits<_manifest_list_json_Union__1__> {
    static void encode(Encoder& e, _manifest_list_json_Union__1__ v) {
        e.encodeUnionIndex(v.idx());
        switch (v.idx()) {
        case 0:
            e.encodeNull();
            break;
        case 1:
            avro::encode(e, v.get_bytes());
            break;
        }
    }
    static void decode(Decoder& d, _manifest_list_json_Union__1__& v) {
        size_t n = d.decodeUnionIndex();
        if (n >= 2) { throw avro::Exception("Union index too big"); }
        switch (n) {
        case 0:
            d.decodeNull();
            v.set_null();
            break;
        case 1:
            {
                std::vector<uint8_t> vv;
                avro::decode(d, vv);
                v.set_bytes(std::move(vv));
            }
            break;
        }
    }
};

template<> struct codec_traits<field_summary> {
    static void encode(Encoder& e, const field_summary& v) {
        avro::encode(e, v.contains_null);
        avro::encode(e, v.contains_nan);
        avro::encode(e, v.lower_bound);
        avro::encode(e, v.upper_bound);
    }
    static void decode(Decoder& d, field_summary& v) {
        if (avro::ResolvingDecoder *rd =
            dynamic_cast<avro::ResolvingDecoder *>(&d)) {
            const std::vector<size_t> fo = rd->fieldOrder();
            for (std::vector<size_t>::const_iterator it = fo.begin();
                it != fo.end(); ++it) {
                switch (*it) {
                case 0:
                    avro::decode(d, v.contains_null);
                    break;
                case 1:
                    avro::decode(d, v.contains_nan);
                    break;
                case 2:
                    avro::decode(d, v.lower_bound);
                    break;
                case 3:
                    avro::decode(d, v.upper_bound);
                    break;
                default:
                    break;
                }
            }
        } else {
            avro::decode(d, v.contains_null);
            avro::decode(d, v.contains_nan);
            avro::decode(d, v.lower_bound);
            avro::decode(d, v.upper_bound);
        }
    }
};

template<> struct codec_traits<manifest_file> {
    static void encode(Encoder& e, const manifest_file& v) {
        avro::encode(e, v.manifest_path);
        avro::encode(e, v.manifest_length);
        avro::encode(e, v.partition_spec_id);
        avro::encode(e, v.content);
        avro::encode(e, v.sequence_number);
        avro::encode(e, v.min_sequence_number);
        avro::encode(e, v.added_snapshot_id);
        avro::encode(e, v.added_data_files_count);
        avro::encode(e, v.existing_data_files_count);
        avro::encode(e, v.deleted_data_files_count);
        avro::encode(e, v.added_rows_count);
        avro::encode(e, v.existing_rows_count);
        avro::encode(e, v.deleted_rows_count);
        avro::encode(e, v.partitions);
    }
    static void decode(Decoder& d, manifest_file& v) {
        if (avro::ResolvingDecoder *rd =
            dynamic_cast<avro::ResolvingDecoder *>(&d)) {
            const std::vector<size_t> fo = rd->fieldOrder();
            for (std::vector<size_t>::const_iterator it = fo.begin();
                it != fo.end(); ++it) {
                switch (*it) {
                case 0:
                    avro::decode(d, v.manifest_path);
                    break;
                case 1:
                    avro::decode(d, v.manifest_length);
                    break;
                case 2:
                    avro::decode(d, v.partition_spec_id);
                    break;
                case 3:
                    avro::decode(d, v.content);
                    break;
                case 4:
                    avro::decode(d, v.sequence_number);
                    break;
                case 5:
                    avro::decode(d, v.min_sequence_number);
                    break;
                case 6:
                    avro::decode(d, v.added_snapshot_id);
                    break;
                case 7:
                    avro::decode(d, v.added_data_files_count);
                    break;
                case 8:
                    avro::decode(d, v.existing_data_files_count);
                    break;
                case 9:
                    avro::decode(d, v.deleted_data_files_count);
                    break;
                case 10:
                    avro::decode(d, v.added_rows_count);
                    break;
                case 11:
                    avro::decode(d, v.existing_rows_count);
                    break;
                case 12:
                    avro::decode(d, v.deleted_rows_count);
                    break;
                case 13:
                    avro::decode(d, v.partitions);
                    break;
                default:
                    break;
                }
            }
        } else {
            avro::decode(d, v.manifest_path);
            avro::decode(d, v.manifest_length);
            avro::decode(d, v.partition_spec_id);
            avro::decode(d, v.content);
            avro::decode(d, v.sequence_number);
            avro::decode(d, v.min_sequence_number);
            avro::decode(d, v.added_snapshot_id);
            avro::decode(d, v.added_data_files_count);
            avro::decode(d, v.existing_data_files_count);
            avro::decode(d, v.deleted_data_files_count);
            avro::decode(d, v.added_rows_count);
            avro::decode(d, v.existing_rows_count);
            avro::decode(d, v.deleted_rows_count);
            avro::decode(d, v.partitions);
        }
    }
};

}
#endif
